name: Build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build
    env:
      RUSTFLAGS: -Awarnings
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1.14.1
        with:
          toolchain: nightly
          target: x86_64-pc-windows-msvc
      - run: rustup target add x86_64-pc-windows-gnu
      - run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: external_dx11_overlay_for_nexus.dll
          path: target/x86_64-pc-windows-msvc/release/external_dx11_overlay_for_nexus.dll